import Head from 'next/head';

type SEOProps = {
    pageTitle?: string;
    font?: string;
};

const SEO = ({ pageTitle, font }: SEOProps) => (
    <Head>
        <title>
            {pageTitle &&
                `${pageTitle} || EduBlink Online Education Platform React Next js Template`}
        </title>
        <meta httpEquiv='x-ua-compatible' content='ie=edge' />
        <meta name='description' content='Generated by create next app' />
        <meta name='robots' content='noindex, follow' />
        <meta
            name='viewport'
            content='width=device-width, initial-scale=1, shrink-to-fit=no'
        />
        {font && <link href={font} rel='stylesheet' />}
        <link rel='icon' href='/favicon.ico' />
    </Head>
);

export default SEO;
